gitRepoUrl = "https://github.com/ItsRune/LootTable"
# classOrder = ["LootTable"]
autoSectionPath = "module"

# Docusaurus settings
[docusaurus]
onBrokenLinks = "warn"
onBrokenMarkdownLinks = "warn"

[footer]
style = "light"
copyright = "Copyright © 2023 ItsRune."

# Footer More
[[footer.links]]
title = "Contact"

[[footer.links.items]]
label = "Developer's Profile"
href = "https://www.roblox.com/users/107392833/profile"

[[footer.links.items]]
label = "Github"
href = "https://github.com/ItsRune/VibezAPI"